const { Pool } = require('pg');

let pool = null;

async function initDatabase() {
  const connectionString = process.env.DATABASE_URL;
  // Managed Postgres (Neon, Render) requires SSL; local Postgres usually doesn't.
  const useSSL = Boolean(connectionString && /neon\.tech|render\.com|sslmode=require/.test(connectionString));

  pool = new Pool({
    connectionString,
    ssl: useSSL ? { rejectUnauthorized: true } : false,
  });

  // Test connection
  const client = await pool.connect();
  try {
    await client.query(`
      CREATE TABLE IF NOT EXISTS trips (
        id SERIAL PRIMARY KEY,
        user_id TEXT NOT NULL,
        city TEXT,
        country TEXT DEFAULT '',
        theme TEXT DEFAULT 'classic',
        transport_mode TEXT DEFAULT 'driving',
        origin_lat DOUBLE PRECISION,
        origin_lng DOUBLE PRECISION,
        places TEXT,
        route_distance DOUBLE PRECISION,
        route_duration DOUBLE PRECISION,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      )
    `);

    await client.query(`
      CREATE INDEX IF NOT EXISTS idx_trips_user_id ON trips(user_id)
    `);

    // Hiking trail support — distinguishes saved POI routes ('route') from
    // saved single trails ('hiking'). Idempotent so existing rows stay valid.
    await client.query(`
      ALTER TABLE trips ADD COLUMN IF NOT EXISTS trip_type TEXT DEFAULT 'route'
    `);

    // Programmatic SEO pages, pre-generated by scripts/generateSeoPages.js and
    // served from DB by /ciudad/:slug/:variant. Only status='published' rows
    // are ever served or listed in the sitemap; 'rejected' rows keep the
    // reason so reruns can retry them.
    await client.query(`
      CREATE TABLE IF NOT EXISTS seo_pages (
        id SERIAL PRIMARY KEY,
        city_slug TEXT NOT NULL,
        page_type TEXT NOT NULL,
        status TEXT NOT NULL,
        reject_reason TEXT,
        title TEXT,
        meta_description TEXT,
        intro TEXT,
        content JSONB NOT NULL DEFAULT '[]'::jsonb,
        total_distance_m INTEGER,
        generated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        UNIQUE (city_slug, page_type)
      )
    `);

    await client.query(`
      CREATE INDEX IF NOT EXISTS idx_seo_pages_lookup ON seo_pages(status, city_slug, page_type)
    `);

    console.log('Database connected and initialized');
  } finally {
    client.release();
  }

  return pool;
}

function getPool() {
  return pool;
}

async function query(sql, params = []) {
  const result = await pool.query(sql, params);
  return result;
}

module.exports = { initDatabase, getPool, query };
